### ISSUE TITLE
预览弹窗优化

### ISSUE THREAD

**Issue by Tray2499** [u-Sir/peek-pop#20]
当前如果使用悬停预览打开一个弹窗，之后在这个打开的页面里继续使用悬停打开弹窗，之前的悬停弹窗并不会关闭，此时就有了两个打开的悬停弹窗，那么当前弹窗失去焦点的时候，只会关闭当前悬停弹窗，之前的悬停弹窗并不会自动关闭。希望能对这个关闭做一个优化。

另外找到一个类似的付费插件，他的预览窗口样式做的蛮不错的，希望能对后续优化做参考

[MaxFocus: 链接预览和AI助手 - Chrome 应用商店](https://chromewebstore.google.com/detail/maxfocus-%E9%93%BE%E6%8E%A5%E9%A2%84%E8%A7%88%E5%92%8Cai%E5%8A%A9%E6%89%8B/bnacincmbaknlbegecpioobkfgejlojp)

**Comment by u-Sir** [comment]
关于自动关闭，会考虑增加相关选项
关于窗口样式，由于实现方式不同，使用的是浏览器本身的界面，因此无法提供，火狐浏览器可以通过 userchrome.css 自行调整

**Comment by u-Sir** [comment]
0.0.36 现已调整自动关闭为：同步关闭下级弹窗，点击原窗口，其所有所属的下级弹窗全部一起关闭。插件目前已上传到火狐、谷歌商店。
