### ISSUE TITLE
macos 13.7 下使用edge安装本插件bug

### ISSUE THREAD

**Issue by langoyb** [u-Sir/peek-pop#22]
窗口最大化的情况下，不管用的哪种弹出方式，均会新开一个最大化窗口出来。原始窗口不是最大化的情况下则新开窗口不会置顶，这两个问题在windows下就不会出现。
不过也很感谢作者了，这种插件还是挺有用的。

**Comment by u-Sir** [comment]
最大化那个应该是 macOS 自身的设定，改不了，这个插件是基于弹窗的，所以是一个新窗口。macOS 的最大化应该是对应 Windows 下在浏览器中按 F11 的那种全屏状态，不过在 Windows 下可以正常弹窗，不过同时会显示任务栏。

置顶这个，你有在插件的设置页面中勾选过后台打开吗？我用 Chrome 测试的正常

**Comment by langoyb** [comment]
chrome 倒还没试过，因为平时不常用。很感谢回复，我去试试。如果正常，那就是 edge 挑嘴了

**Comment by u-Sir** [comment]
这个问题，没回复，我先关闭了
