### ISSUE TITLE
移动链接至书签栏时会弹出小窗

### ISSUE THREAD

**Issue by xpetrichor** [u-Sir/peek-pop#23]
能让它移动到书签栏时不弹出小窗吗

https://github.com/user-attachments/assets/f4b03532-67bb-4631-a5d3-1e33f7037001

**Comment by u-Sir** [comment]
感谢反馈，会尝试修复

**Comment by u-Sir** [comment]
0.0.36 上应该修复了这个问题。目前已上传到火狐、谷歌商店。

**Comment by xpetrichor** [comment]
多谢修复
