### ISSUE TITLE
拖拽弹出的小窗链接是上一个拖拽链接

### ISSUE THREAD

**Issue by xpetrichor** [u-Sir/peek-pop#24]
这个问题我在应用商店提过

https://github.com/user-attachments/assets/3a68639f-3e12-419c-8a00-357c2f252bdc

**Comment by u-Sir** [comment]
嗯，这个我会尝试在下版修

**Comment by u-Sir** [comment]
方便测试下这个包吗？需要先禁用原来的插件再加载
https://github.com/user-attachments/files/17606585/peekpop_demo-110218.zip
![图片](https://github.com/user-attachments/assets/246656b8-5431-40ea-8646-111ca5ba9d19)

**Comment by xpetrichor** [comment]
现在好像好了，暂时触发不出来，不过之前我都是正常用一小段时间后突然就出问题了。等我使用一整天看看，如果今天没有再触发，那应该就是没有问题了。

**Comment by xpetrichor** [comment]
> 方便测试下这个包吗？需要先禁用原来的插件再加载 https://github.com/user-attachments/files/17606585/peekpop_demo-110218.zip ![图片](https://private-user-images.githubusercontent.com/93647031/382518797-246656b8-5431-40ea-8646-111ca5ba9d19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MDMzNTgsIm5iZiI6MTczMDYwMzA1OCwicGF0aCI6Ii85MzY0NzAzMS8zODI1MTg3OTctMjQ2NjU2YjgtNTQzMS00MGVhLTg2NDYtMTExY2E1YmE5ZDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDAzMDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NzNmYjgzNjQ1ZjhlNjEwMDZjYjkwY2E3ODQ0ZjNmY2M3NTA3YmRjYTIyY2M4OTM4ZjRlMDRiZDczMTc3YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KcBzzvh14dMCj5CNVwbWOLnrvd4D7ModLd2L_BmqaS0)

等等，它好像触发了一个新问题，youtube视频播放时双击不能全屏和退出全屏了

**Comment by u-Sir** [comment]
> > 方便测试下这个包吗？需要先禁用原来的插件再加载 https://github.com/user-attachments/files/17606585/peekpop_demo-110218.zip ![图片](https://private-user-images.githubusercontent.com/93647031/382518797-246656b8-5431-40ea-8646-111ca5ba9d19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MDMzNTgsIm5iZiI6MTczMDYwMzA1OCwicGF0aCI6Ii85MzY0NzAzMS8zODI1MTg3OTctMjQ2NjU2YjgtNTQzMS00MGVhLTg2NDYtMTExY2E1YmE5ZDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDAzMDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NzNmYjgzNjQ1ZjhlNjEwMDZjYjkwY2E3ODQ0ZjNmY2M3NTA3YmRjYTIyY2M4OTM4ZjRlMDRiZDczMTc3YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KcBzzvh14dMCj5CNVwbWOLnrvd4D7ModLd2L_BmqaS0)
> 
> 等等，它好像触发了一个新问题，youtube，哔哩哔哩视频播放时双击不能全屏和退出全屏了

啊这，我再看下👀

**Comment by xpetrichor** [comment]
> 现在好像好了，暂时触发不出来，不过之前我都是正常用一小段时间后突然就出问题了。等我使用一整天看看，如果今天没有再触发，那应该就是没有问题了。

好吧，现在又触发了

**Comment by xpetrichor** [comment]
而且都是本网站的上一个链接，换到另一个网站就是另一个网站的上一个链接了

**Comment by xpetrichor** [comment]
https://github.com/user-attachments/assets/fdb1a8d0-bbd3-45f3-b77d-6cf1e09e012d

**Comment by u-Sir** [comment]
@xpetrichor 其它触发方式也会出现这情况吗？

**Comment by u-Sir** [comment]
[peekpop_demo-110313.zip](https://github.com/user-attachments/files/17609442/peekpop_demo-110313.zip)
再帮忙试下这版

**Comment by xpetrichor** [comment]
> @xpetrichor 其它触发方式也会出现这情况吗？


点击和悬停之前没怎么用，现在似乎在拖拽会触发的情况下这两个都不会触发，等我用一段时间再看看

https://github.com/user-attachments/assets/e4d13c1b-ddba-48f1-bce0-12afc3c4e6d0

**Comment by xpetrichor** [comment]
> [peekpop_demo-110313.zip](https://github.com/user-attachments/files/17609442/peekpop_demo-110313.zip) 再帮忙试下这版

我试试，不过估计得等一段时间才能知道有没有问题

**Comment by xpetrichor** [comment]
果然，又复现了

**Comment by xpetrichor** [comment]
刷新了一下网页，好像又正常了，之前的版本刷新了也还是没用

**Comment by xpetrichor** [comment]
还有一个问题，似乎拖拽得越远加载得就越慢

https://github.com/user-attachments/assets/83eb9373-0a70-4e04-8e27-f9c97898c211

**Comment by u-Sir** [comment]
> 刷新了一下网页，好像又正常了，之前的版本刷新了也还是没用，没那么容易触发了

[peekpop_demo-110318.zip](https://github.com/user-attachments/files/17609945/peekpop_demo-110318.zip)

这版出现问题时，帮忙按 F12，点击 console，把里面的信息发一下

![图片](https://github.com/user-attachments/assets/a43a94c2-024b-445a-a93a-9bab22fcb2eb)

我在虚拟机上好难复现 😂，目前只遇到一次

**Comment by xpetrichor** [comment]
不太清楚，这版就那一次触发了，到现在都没触发第二遍。跟别的扩展应该也没关系，我之前关了所有的扩展也还是会触发。而且之前的版本应该是不会“拖拽得越远加载得就越慢”，只有这版有

**Comment by xpetrichor** [comment]
> > 刷新了一下网页，好像又正常了，之前的版本刷新了也还是没用，没那么容易触发了
> 
> [peekpop_demo-110318.zip](https://github.com/user-attachments/files/17609945/peekpop_demo-110318.zip)
> 
> 这版出现问题时，帮忙按 F12，点击 console，把里面的信息发一下
> 
> ![图片](https://private-user-images.githubusercontent.com/93647031/382562140-a43a94c2-024b-445a-a93a-9bab22fcb2eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzAxMjAsIm5iZiI6MTczMDYyOTgyMCwicGF0aCI6Ii85MzY0NzAzMS8zODI1NjIxNDAtYTQzYTk0YzItMDI0Yi00NDVhLWE5M2EtOWJhYjIyZmNiMmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDEwMzAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjOTNiYmI0ZTBkMWMwMThiZGYxN2IxMDUzYjA1NzE4N2VhZGQyODk4MWY5MTA5OGJhZmJkOGYwOWJjY2M4MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.brrFheH22a01AUcL2WJ0Y1KS3sA7uc_QXu0BFhAE8_0)
> 
> 我在虚拟机上好难复现 😂，目前只遇到一次。 你有观察到啥必现的触发流程吗？

成功触发
[www.appinn.com-1730630152919.log](https://github.com/user-attachments/files/17610061/www.appinn.com-1730630152919.log)

**Comment by xpetrichor** [comment]
我好像发现了，拖拽的距离非常短的时候很容易触发

**Comment by u-Sir** [comment]
> 我好像发现了，拖拽的距离非常短的时候很容易触发，只挪动一点点那种，然后就会无论拖拽长短都会触发了

十分感谢，貌似确实可以复现到了 👍

**Comment by xpetrichor** [comment]
而且触发后，清除掉网站的数据和cookie就会暂时恢复正常，然后过一段时间再次触发

**Comment by u-Sir** [comment]
0.0.36 上应该修复了这个问题。目前已上传到火狐、谷歌商店。

**Comment by xpetrichor** [comment]
感谢，但好像还残留着之前的这一个小问题

> 还有一个问题，似乎拖拽得越远加载得就越慢
> 
>  QQ2024113-16245.-.Compressed.with.FlexClip.mp4

**Comment by u-Sir** [comment]
这个我这边没啥感觉 😂，方便帮忙测试下？
方便到设置页面导出配置分享下？
停用其它插件是否也一样？
删除重新安装是否也一样？

**Comment by xpetrichor** [comment]
[](url)

https://github.com/user-attachments/assets/0675dd7d-e0e1-4f80-af9d-3189c2368860

拖拽到最近距离是秒开，拖到最远和最近差个2-3秒这样

**Comment by xpetrichor** [comment]
> 这个我这边没啥感觉 😂，方便帮忙测试下？ 方便到设置页面导出配置分享下？ 停用其它插件是否也一样？ 删除重新安装是否也一样？
配置是默认的没有调
停用其它插件也是一样
删除重新安装也是一样

**Comment by xpetrichor** [comment]
用的是Chrome，Edge还没试，我试试

**Comment by xpetrichor** [comment]
Edge没有这个问题，远近都是秒开

**Comment by u-Sir** [comment]
Chrome 版本是多少？

**Comment by xpetrichor** [comment]
Firefox好像也有点问题，打开小窗的同时会同时打开新标签页，而且有时候还弹不出小窗

**Comment by u-Sir** [comment]
> Firefox好像也有点问题，打开小窗的同时会同时打开新标签页，而且有时候还弹不出小窗

啊这，版本是？有注意到啥必现的方法吗？

**Comment by xpetrichor** [comment]
> > Firefox好像也有点问题，打开小窗的同时会同时打开新标签页，而且有时候还弹不出小窗
> 
> 啊这，版本是？有注意到啥必现的方法吗？

没事了，我把其他拓展都关了就好了，应该是其他拓展的问题

**Comment by xpetrichor** [comment]
Chrome的这个问题能解决吗？

**Comment by u-Sir** [comment]
> Chrome的这个问题能解决吗？

我也不清楚，有空再看看 😂，按理应该跟 Edge 一样呀，代码都是同一份

**Comment by u-Sir** [comment]
> > > Firefox好像也有点问题，打开小窗的同时会同时打开新标签页，而且有时候还弹不出小窗
> > 
> > 
> > 啊这，版本是？有注意到啥必现的方法吗？
> 
> 没事了，我把其他拓展都关了就好了，应该是其他拓展的问题，而且Firefox也是秒开，只有Chrome有这个问题

这个是跟哪个插件冲突了？

**Comment by xpetrichor** [comment]
> > > Firefox好像也有点问题，打开小窗的同时会同时打开新标签页，而且有时候还弹不出小窗
> > 
> > 
> > 啊这，版本是？有注意到啥必现的方法吗？
> 
> 没事了，我把其他拓展都关了就好了，应该是其他拓展的问题，而且Firefox也是秒开，只有Chrome有这个问题

找到问题了，是这个
![屏幕截图 2024-12-08 214525_看图王(1)](https://github.com/user-attachments/assets/39368c10-26d1-4de5-b689-dd7ddc46fba4)

**Comment by u-Sir** [comment]
你这个插件貌似都下架了 😂

**Comment by xpetrichor** [comment]
不懂，一直丢在这没管过

**Comment by u-Sir** [comment]
这个单我关闭了，拖拽远近的那个问题我会留意下
