### ISSUE TITLE
一些网站小窗预览会返回主页

### ISSUE THREAD

**Issue by xpetrichor** [u-Sir/peek-pop#25]
https://github.com/user-attachments/assets/431c4fc6-3cc5-4199-bc9e-7a8f65561074

**Comment by u-Sir** [comment]
还有类似情况的网站吗？都提供下网址

**Comment by xpetrichor** [comment]
现在只发现了这个网站会这样
https://1207fabu.top/

**Comment by xpetrichor** [comment]
这个网站的链接我用Chrome拖拽不了，但用Firefox可以，不知道是不是我的问题
https://assrt.net/

**Comment by u-Sir** [comment]
> 现在只发现了这个网站会这样 https://1207fabu.top/

这网站在 Arc 上预览也一样会跳转到主页，貌似网站有做特殊的处理，手动通过右键复制条目的链接，然后粘贴到地址栏上，回车后也是跳转到主页的，太 6 了，感觉我解决不了 😂

**Comment by u-Sir** [comment]
> 这个网站的链接我用Chrome拖拽不了，但用Firefox可以，不知道是不是我的问题 https://assrt.net/

这个我这边也一样，到时再看看

**Comment by xpetrichor** [comment]
> > 这个网站的链接我用Chrome拖拽不了，但用Firefox可以，不知道是不是我的问题 https://assrt.net/
> 
> 这个我这边也一样，到时再看看

我觉得可能是浏览器的问题，因为就算不用扩展也拖拽不了

**Comment by u-Sir** [comment]
这个应该是网站那边的设置，插件解决不了，我关闭单了

**Comment by xpetrichor** [comment]
我发现NoTab这个插件没有这个问题，他是怎么实现的？https://notab.wand.tools/zh
