### ISSUE TITLE
关于拖拽设置的几个建议

### ISSUE THREAD

**Issue by wha4up** [u-Sir/peek-pop#26]
1. 增加不响应按键选项
拖拽预览是个很棒的扩展，目前已成为我浏览网页的日常操作，契合大多数的拖拽需求，但有小部分需求是不需要打开弹窗的，比如拖拽到页面的搜索框。目前的设置暂时无法满足临时不执行的响应的操作，故希望能不响应按键选项。

2. 增加超过移动距离不执行选项，或将移动距离改为区间设置
这个需求还是和上面的有关。大多数页面搜索框是在页面的顶部，鼠标移动距离是较大的，目前仅支持超过距离执行的设置并不能在执行该操作时排除，故希望能有所调整。

3. 拖拽方向支持不同的搜索引擎

另外不知道弹窗形式能不能实现打开为侧边栏且固定住，或许写东西查对资料的时候有需求。

**Comment by u-Sir** [comment]
1、2 这两个会考虑下，不一定会添加，如果你是高频预览的话，下一版的点击=>预览、双击=>普通单击，不触发预览，可能更适合，且不会影响拖拽功能。有兴趣可以先试下，不知你能不能接受这种操作，这个是我拆分出来上架到火狐上自用： https://addons.mozilla.org/zh-CN/firefox/addon/peek-pop-onclick/

3 这个下一版会添加一个搜索条来解决，而不是通过拖拽方向，不过暂不能自定义，你常用哪些搜索引擎呢？
目前可以自行配合其它拖拽插件来解决，根据需要自行指定下方向即可，一般不会有冲突
![image](https://github.com/user-attachments/assets/fbe2ad04-b63f-4f76-92b2-ae58a1ec9c6b)

不知你用的什么系统和浏览器，最后侧边栏这个暂时应该不会考虑，如果是 Edge 的话，自带有分屏功能的，可能更加适合。
![image](https://github.com/user-attachments/assets/8f2a6445-a21c-4f0c-aaa7-70f34ac645bf)
![image](https://github.com/user-attachments/assets/e7a8fca1-b41a-4f77-b852-c46327298adc)

**Comment by u-Sir** [comment]
搜索条大概这个样子
![image](https://github.com/user-attachments/assets/d636ec1d-35a2-46c6-b665-0967288afb14)

**Comment by u-Sir** [comment]
关于临时终止预览这个，下版在拖拽释放时会检查下是否有多余的修饰键是否有按下，如果有的话就不预览，例如： 拖拽的修饰键是"无"，这时只需随便按住一个修饰键再释放就不会显示预览

**Comment by u-Sir** [comment]
0.0.36 现在可以打断预览了。目前已上传到火狐、谷歌商店，可更新试下。
