### ISSUE TITLE
Pop-up window not centered with latest version 0.0.31 (all versions after 0.0.26)

### ISSUE THREAD

**Issue by aquarime** [u-Sir/peek-pop#28]
Hi,

Peek-Pop 0.0.31 / Firefox 115.18.0 ESR

I'm facing the same issue that had been reported and fixed at https://github.com/u-Sir/peek-pop/issues/5
In the extension's Popup Window Settings:
Double-tap = None
Check-boxes : all disabled (hence including 'Try to open at mouse position')
Only height and width are set.
The popup window should therefor be displayed centered. It is not centered but always positioned top-left.

To be sure there is no conflict between ver. 0.0.26 and 0.0.31 I did a clean install of 0.0.31 : issue remained.
Uninstalled 0.0.31, reinstalled 0.0.26 : no more issue of course.

**Comment by u-Sir** [comment]
Thank you, I’ll check it.
In the meantime, please disable auto-update on the Add-ons page until the issue is fixed.
![image](https://github.com/user-attachments/assets/dee6cd40-990e-4514-99cf-1913cb048edc)

**Comment by aquarime** [comment]
Thanks for your quick reply and for checking.
Automatic Updates are off by default here. We stick for the time being on 0.0.26 and will be careful to uncheck 'Drag to Preview' when checking manually for updates.
I stay tuned.

**Comment by aquarime** [comment]
I just updated (manually) from _Drag tp Preview_ 0.0.26 to _Peek Pop 0.0.32_ and popup window is now correctly centered.
I'll rename the title.
That was a quick fix :)

**Comment by u-Sir** [comment]
There’s one more fix related to the zoom issue in version 0.0.33 now. 😆

**Comment by aquarime** [comment]
OK. Updated to 0.0.33. No idea what the zoom feature is so I couldn't have noticed an issue.
Nice work, as always. By the way : the centered popup windoww issue fixed with 0.0.32 remains fixed with 0.0.33 : I point it out because in my experience it happens that one fix destabilizes a previous fix :) Unless no relation between both, of course.
Well, all is fine at this stage as far as I'm concerned.
