### ISSUE TITLE
Please a feature to pin popup window

### ISSUE THREAD

**Issue by IkramHussainSiyam** [u-Sir/peek-pop#29]
# There are many extensions on this chrome website preview, but this is by far the best I've found. 

## Reasons I love this extension 💖:

1. Extension works in popup preview: on other extension of link preview extension of chrome doesn't work and causes problem for me.
2. It's popup not custom random windows like other extensions
3. Customization of this extensions option are great

## 🔴 Now the Problem 🔴:
In one of those extensions available in chrome webstore is MaxFocus, and they have a feature that i can pin the popup on open. Meaning if i hover or drag a link and it opens a popup, it'll be automatically pinned so it'll stay on the screen(s) top.

### The solution I'd like to request
I request you add a feature or option in **-Extensions option-** that I can have a choice whether i should pin popup on open or not.

### Additional context
If you want to know about this feature look into this extension.
MaxFocus: https://maxfoc.us/

**Comment by u-Sir** [comment]
Thank you for your feedback! 

Currently, my extension is based on window popups, meaning it operates independently of the webpage and doesn't integrate directly into the page. Unfortunately, there’s no API available to set the popup to "always on top." This is why I can’t implement a pinning feature like MaxFocus.
Regarding Always-on-Top:

If you want a popup to stay "always on top" for tabs or windows, it’s not possible directly via extensions. However, you can use third-party software like PowerToys to achieve this functionality.
Preventing Auto-Close:

If your concern is about the preview closing automatically:

    You can disable the “close popup when original window is focused” option in the extension settings.
    Based on your suggestion, I will also consider adding a button on the preview page to prevent auto-close, even if the auto-close option is enabled.

I hope this helps! Let me know if you have any other suggestions or questions.

**Comment by IkramHussainSiyam** [comment]
Great suggestion thanks
i never thought about powertoys 
it'll use that for now

**Comment by IkramHussainSiyam** [comment]
#### Great suggestion thanks 💖
I never thought about **PowerToys** 
I'll use that for now
