### ISSUE TITLE
请问功能“禁止弹出以下 URLs ，每行一条规则，支持正则表达式、通配符、纯文本”会生效吗？

### ISSUE THREAD

**Issue by yyy22335** [u-Sir/peek-pop#30]
目前尝试配置https://chatgpt.com和^https://chatgpt\.com.*
好像都依然会触发拖拽预览，特别是chatgpt上线了项目之后，拖拽的行为会大大增加。

或者能否增加一个浏览器拓展配置，点击把该网页加入黑名单？

**Comment by u-Sir** [comment]
`/^https:\/\/chatgpt\.com.*$/`
添加后刷新下网页试下

**Comment by yyy22335** [comment]
好的，加上/解决了
